# Generated by Django 4.1 on 2024-10-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gas_station", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasstation",
            name="current_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="gasstation",
            name="user_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
