# Generated by Django 4.1 on 2024-10-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gas_station", "0002_alter_gasstation_current_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasstation",
            name="reviews",
            field=models.TextField(blank=True, default="No reviews yet"),
            preserve_default=False,
        ),
    ]
