# Generated by Django 4.1 on 2024-11-04 19:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gas_station", "0003_alter_gasstation_reviews"),
    ]

    operations = [
        migrations.RemoveField(model_name="gasstation", name="latitude",),
        migrations.RemoveField(model_name="gasstation", name="longitude",),
        migrations.AddField(
            model_name="gasstation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="gasstation",
            name="current_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="gasstation",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gasstation",
            name="user_rating",
            field=models.FloatField(null=True),
        ),
    ]
