services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - awm_django_app
    networks:
      - app_network

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "20080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: bujar.raufi@tudublin.ie
      PGADMIN_DEFAULT_PASSWORD: mypassword
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgis
    networks:
      - app_network
  
  postgis:
    image: kartoza/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_DB: gas_station_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - app_network

  awm_django_app:
    image: gas_station
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgis
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgadmin_data:
  postgis_data:


